<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Utils\Point;
use Doctrine\ORM\Query\Expr\Join;
use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Utils\PointType;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
}
