<?php
/**
 *  Cuisine Repository
 *  @category Repository
 *  @author Jayraj Arora<jayraja@mindfiresolutions.com>
 */
namespace AppBundle\Repository;

/**
 * CuisineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuisineRepository extends \Doctrine\ORM\EntityRepository
{
}
