<?php

namespace AppBundle\Repository;

/**
 * CuisineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuisineRepository extends \Doctrine\ORM\EntityRepository
{
}
