<?php

namespace AppBundle\Repository;

/**
 * InOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
