<?php
/**
 *  InOrder Repository
 *  @category Repository
 *  @author Jayraj Arora<jayraja@mindfiresolutions.com>
 */
namespace AppBundle\Repository;

/**
 * InOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InOrderRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Fetch order item details
     * @param $orderId
     * @return array
     */
    public function fetchOrderItemDetails($orderId)
    {
        $qb = $this->createQueryBuilder('inOrder')
            ->join('inOrder.inRestaurant', 'inRestaurant')
            ->join('inRestaurant.menuItem', 'menuItem')
            ->select('inOrder.quantity')
            ->addSelect('inRestaurant.price')
            ->addSelect('menuItem.name')
            ->andWhere('inOrder.placedOrder = :placedOrderId')
            ->setParameter('placedOrderId', $orderId)
        ;

        return $qb->getQuery()->getArrayResult();
    }
}
