<?php

namespace AppBundle\Repository;

/**
 * InRestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InRestaurantRepository extends \Doctrine\ORM\EntityRepository
{
}
