<?php

namespace AppBundle\Repository;

/**
 * OrderStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
