<?php

namespace AppBundle\Repository;

/**
 * PlacedOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlacedOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
