<?php

namespace AppBundle\Repository;

/**
 * StatusCatalogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusCatalogRepository extends \Doctrine\ORM\EntityRepository
{
}
