app:
    resource: '@AppBundle/Controller/'
    type: annotation

eat24_1.0_restaurant:
    resource: "@AppBundle/Controller/API/V10/Restaurant/"
    type:     annotation
    prefix:   /1.0/eat24/restaurant
    defaults: {"_format": "json"}

eat24_1.0_user:
    resource: "@AppBundle/Controller/API/V10/User/"
    type:     annotation
    prefix:   /1.0/eat24/user
    defaults: {"_format": "json"}

eat24_1.0_order:
    resource: "@AppBundle/Controller/API/V10/Order/"
    type:     annotation
    prefix:   /1.0/eat24/order
    defaults: {"_format":"json"}

eat24.swagger_ui:
    path: /api/doc/
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }