security:

    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm:           sha1
            encode_as_base64:    false
            iterations:          1

    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            anonymous: true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control: ~